#cloud-config

users:
  - name: developer
    groups: sudo, www-data
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - {ssh-pubkey}

package_upgrade: true

packages:
  - nginx

snap:
  commands:
    - snap install node --classic --channel 14/stable

timezone: Europe/Athens

write_files:
  - path: /etc/nginx/sites-available/app.test
    content: "server {

      listen 80;

      listen [::]:80;

      root /home/developer/repo/dist;

      index index.html home.html comparison.html application.html contact-us.html;

      server_name app.test www.app.test;

      # kill cache

      add_header Last-Modified $date_gmt;

      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';

      if_modified_since off;

      expires off;

      etag off;

      #error_log /var/log/nginx/debug.log debug;

}"

runcmd:
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - mkdir -p /home/developer/repo/dist/
  - chown -R developer:developer /home/developer/repo/
  - sed -i -e 's#      \*) return;;#      \*) source /etc/profile\.d/apps\-bin\-path\.sh; cd ~/repo/; return;;#g' /home/developer/.bashrc
  - service ssh restart
  - ln -s /etc/nginx/sites-available/app.test /etc/nginx/sites-enabled/
  - echo '127.0.0.1  app.test' >> /etc/hosts
  - service nginx reload
  - ufw allow OpenSSH
  - ufw allow "Nginx Full"
  - ufw allow 3000 # browsersync (livereload)
  - ufw allow 3001 # browsersync (admin ui)
  - ufw enable

final_message: "The system is finally up, after $UPTIME seconds"
